# Generated by Django 5.0.7 on 2024-07-31 14:31

import accounts.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_account_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='account',
            managers=[
                ('objects', accounts.managers.UserManager()),
            ],
        ),
    ]
